MvcBlog/Controllers/Admin/BlogAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MvcBlog.Models;
using MvcBlog.Domain;
using MvcBlog.Domain.Entities;



namespace MvcBlog.Controllers.Admin
{
    public class BlogAdminController : Controller
    {

        private IBlogManager _blogManager;
        private IDBHelper _dbHelper;

        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="manager"></param>
        public BlogAdminController(IBlogManager manager, IDBHelper helper)
        {
            //ninject: inject implementation
            _blogManager = manager;
            _dbHelper = helper;
        }



        //
        // GET: /BlogAdmin/Index
        [Authorize(Roles = "Admin")]
        [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult Index()
        {
            string searchToken = string.Empty;
            if((HttpContext.Request.QueryString != null) && (HttpContext.Request.QueryString["searchToken"] != null))
            {
                searchToken = HttpContext.Request.QueryString["searchToken"].ToString();
            }

            var blogs = _blogManager.GetAllBlogs(string.IsNullOrEmpty(searchToken) ? null : searchToken);
            blogs.ForEach(PrepareBlogList);
            
            BlogsViewModel model = new BlogsViewModel
            {
                BlogList = blogs
            };


            return View(model);
        }

        //
        // GET: /BlogAdmin/BlogList/        
        public ActionResult BlogList()
        {
            
            BlogsViewModel model = new BlogsViewModel
            {
                BlogList = _blogManager.GetAllBlogs()
            };


            return View(model);
        }

        //
        // GET: /BlogAdmin/Tags/        
        [Authorize(Roles = "Admin")]
        public ActionResult Tags()
        {

            BlogsViewModel model = new BlogsViewModel
            {
                TagList = _dbHelper.GetTags()
            };


            return View(model);
        }

        //
        // GET: /BlogAdmin/TalkBacks/1  
        [Authorize(Roles = "Admin")]
        public ActionResult TalkBacks(int id)
        {
            BlogsViewModel model = new BlogsViewModel
            {
                NewBlog = _blogManager.GetBlog(id)//reuse NewBlog just to store blog ID
            };

            return View(model);
        }


        //
        // GET: /CreateBlog/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var selectItems = new SelectList(_dbHelper.GetCategories(), "Id", "Name");

            BlogsViewModel model = new BlogsViewModel
            {
                BlogList = _blogManager.GetAllBlogs(),
                CategoryList = selectItems
            };

            return View(model);
        }

        //
        // POST: /CreateBlog/Create

        [HttpPost]
        [ValidateInput(false)] /*this works in conjunction with web.config value requestValidationMode="2.0" http://msdn.microsoft.com/en-us/library/hh882339.aspx */
        [Authorize(Roles = "Admin")]
        //Custom binder if needed
        public ActionResult Create([ModelBinder(typeof(BlogModelBinder))]MvcBlog.Domain.Entities.Blog newBlog, FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Please, try again!");

                var selectItems = new SelectList(_dbHelper.GetCategories(), "Id", "Name");

                BlogsViewModel model = new BlogsViewModel
                {
                    BlogList = _blogManager.GetAllBlogs(),
                    CategoryList = selectItems,
                    NewBlog = newBlog
                };


                return View(model);
            }

            try
            {
                newBlog.CreatedDate = DateTime.Now;
                newBlog.ModifiedDate = DateTime.Now;

                int res = _blogManager.CreateBlog(newBlog);
                
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw new HttpException(500, "Create failed.");
            }
        }

        //
        // GET: /CreateBlog/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var selectItems = new SelectList(_dbHelper.GetCategories(), "Id", "Name");

            MvcBlog.Domain.Entities.Blog blog = _blogManager.GetBlog(id);

            BlogsViewModel model = new BlogsViewModel
            {
                BlogList = _blogManager.GetAllBlogs(),
                CategoryList = selectItems,
                NewBlog = blog,
                CategoryId = blog.CategoryId
            };

            return View(model);
        }

        //
        // POST: /CreateBlog/Edit/5

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateInput(false)]
        public ActionResult Edit([ModelBinder(typeof(BlogModelBinder))]MvcBlog.Domain.Entities.Blog blog, FormCollection collection)
        //public ActionResult Edit(MvcBlog.Domain.Entities.Blog blog, FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Please, try again!");

                var selectItems = new SelectList(_dbHelper.GetCategories(), "Id", "Name");

                BlogsViewModel model = new BlogsViewModel
                {
                    BlogList = _blogManager.GetAllBlogs(),
                    CategoryList = selectItems,
                    NewBlog = blog
                };


                return View(model);
            }


            try
            {
                blog.ModifiedDate = DateTime.Now;
                
                _blogManager.UpdateBlog(blog);
                
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw new HttpException(500, "Update failed.");
            }
        }


        //
        // POST: /CreateBlog/Delete/5

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _blogManager.DeleteBlog(id);

                return RedirectToAction("Index");

            }
            catch
            {
                throw new HttpException(500, "Delete failed.");
            }
        }

        /// <summary>
        /// Format Body and Description
        /// </summary>
        /// <param name="blog"></param>
        private static void PrepareBlogList(MvcBlog.Domain.Entities.Blog blog)
        {
            if (!string.IsNullOrEmpty(blog.Body))
            {
                if (blog.Body.Length > 30)
                {
                    blog.Body = blog.Body.Substring(0, 30) + "..";
                }
                else
                {
                    //do nothing
                }
            }

            if (!string.IsNullOrEmpty(blog.Description))
            {
                if (blog.Description.Length > 30)
                {
                    blog.Description = blog.Description.Substring(0, 30) + "..";
                }
                else
                {
                    //do nothing
                }
            }
        
        }
    }
}

MvcBlog/Controllers/Admin/BlogAdminHelperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;

using MvcBlog.Models;
using MvcBlog.Domain;
using MvcBlog.Domain.Entities;

namespace MvcBlog.Controllers.Admin
{
    public class BlogAdminHelperController : Controller
    {

        private IBlogManager _blogManager;
        private IDBHelper _dbHelper;


        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="manager"></param>
        public BlogAdminHelperController(IBlogManager manager, IDBHelper helper)
        {
            //ninject: inject implementation
            _blogManager = manager;
            _dbHelper = helper;

        }

        //
        // GET: /Index/
        public PartialViewResult Index()
        {
            BlogsViewModel model = new BlogsViewModel
            {
                BlogList = _blogManager.GetAllBlogs().OrderByDescending(p=>p.CreatedDate).ToList()
            };

            return PartialView(model);
        }

        //
        // GET: /TagList/

        public PartialViewResult TagList(List<MvcBlog.Domain.Entities.Tag> tagList)
        {
            return PartialView(tagList);
        }

        public PartialViewResult TagListCommaSeparated(List<MvcBlog.Domain.Entities.Tag> tagList)
        {
            StringBuilder sb = new StringBuilder();

            foreach (Tag t in tagList)
            {
                sb.Append(t.Name + ",");
            }

            string final = sb.ToString();

            if (final.Length > 0)
            {
                final = final.Remove(final.Length - 1, 1);
            }

            ViewBag.TagList = "<input type=\"text\" value = \""  + final + "\" id=\"Tags\" name=\"Tags\" />";

            return PartialView();
        }



        public PartialViewResult TagListFull()
        {
            List<MvcBlog.Domain.Entities.Tag> tagList = _dbHelper.GetTags().OrderBy(p => p.Name).ToList();

            StringBuilder sb = new StringBuilder();
            sb.Append("<table style=\"width:200px;\" id=\"box-table-a\">\r\n");

            int count = tagList.Count / 3;

            if (tagList.Count % 3 != 0)
            {
                count++;
            }

            int k = 0;

            for (int i = 0; i < count; i++)
            {
                if (k > tagList.Count)
                    break;

                sb.Append("<tr>\r\n");

                for (int j = 0; j < 3; j++)
                {
                    if (k >= tagList.Count)
                    {
                        break;
                    }


                    sb.Append("<td>");

                    string url = Url.Action("Index", "Tag", new { id = string.Format("{0}", tagList[k].Id) });
                    sb.Append(string.Format("<a href=\"{0}\">", url) + tagList[k].Name + "</a>");
                    sb.Append("</td>\r\n");

                    k++;
                }                

                sb.Append("</tr>\r\n");

            }

            sb.Append("</table>");

            ViewBag.FormatedString = sb.ToString(); ;


            return PartialView();
        }

   
    }
}

MvcBlog/Views/Shared/_BlogAdminLayout.cshtml
@model MvcBlog.Models.BlogsViewModel

<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8" />
	<title>@ViewBag.Title - Blogs Application</title>
	<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<meta name="viewport" content="width=device-width" />
	
	@Styles.Render("~/Content/css")
	

	<!--TODO-->
	<link href="~/Controls/markitup/skins/markitup/style.css" rel="stylesheet" />
	<link href="~/Controls/markitup/sets/default/style.css" rel="stylesheet" />
	
	<link href="~/Content/buttons.css" rel="stylesheet" />


	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryval")



	@Scripts.Render("~/bundles/modernizr")
	
	<script src="~/Controls/markitup/jquery.markitup.js" ></script>
	<script src="~/Controls/markitup/sets/default/set.js" ></script>

	<script>

		$(document).ready(function () {

			var controller = '@ViewContext.RouteData.Values["Controller"]';
			var action = '@ViewContext.RouteData.Values["Action"]';

			if ((action != "Index") && (controller == 'BlogAdmin')) {

				var id = '';

				switch (action) {

					case 'Tags':
						 id = "Cat_" + 'Tags';
						break;
					case 'Create':
						id = "Cat_" + 'Blog';
						break;
				}

				$("#" + id).addClass("selected_category");
			}
			else {
				if (controller == 'BlogAdmin')
					$("#Cat_Home").addClass("selected_category");
			}


		});

	</script>


</head>
	

<body>

	<div id="header">
		<h1>Smart Blog</h1>
		<ul>
			<li><a id="Cat_Home" href="~/BlogAdmin/">Admin Home</a></li>
			<li><a id="Cat_Blog" href="~/BlogAdmin/Create">Create New Blog</a></li>
			<li><a id="Cat_Tags" href="~/BlogAdmin/Tags">Manage Tags</a></li>
		</ul>
		<p id="layoutdims_admin">
			<span style="float:left;">Welcome @HttpContext.Current.User.Identity.Name</span>
			@Html.ActionLink("Log out", "LogOut", "Account")
		</p>
	</div>
	<div class="colmask leftmenu">
		<div class="colleft">
			<div class="col1">
				<!-- Column 1 start -->

				<div id="body">
					@RenderBody()
				</div>

				<!-- Column 1 end -->
			</div>
			<div class="col2">
				<!-- Column 2 start -->
				<div id="ads">
					<a href="~/Home">
						<img src="@Url.Content("~/Images/BlogImage.jpg")" width="125" border="0" height="125" alt="" />
					</a>
				</div>
				<h2>Latest Blogs</h2>


				<!--Blog list (last 10..) -->
				@{Html.RenderAction("Index", "BlogAdminHelper");}
				<!-- Column 2 end -->
			</div>
		</div>
	</div>
	<div id="footer">
		<p>Alexey Geller, 2012-2013</p>
	</div>



	@RenderSection("scripts", required: false)
</body>
</html>

MvcBlog/Views/Shared/_BlogLayout.cshtml
@model MvcBlog.Models.HomePageModel

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>@ViewBag.Title - Blogs Application</title>
		<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
		<meta name="viewport" content="width=device-width" />
		@Styles.Render("~/Content/css")
		
		<!--TODO-->
		<link href="~/Content/buttons.css" rel="stylesheet" />


		@Scripts.Render("~/bundles/jquery")
		@Scripts.Render("~/bundles/jqueryval")

		@Scripts.Render("~/bundles/modernizr")


		<script>


			$(document).ready(function () {
				//get Category Id
				var id = '@ViewContext.RouteData.Values["id"]';
				var controller = '@ViewContext.RouteData.Values["Controller"]';

				if ((id != "") && (controller == 'Home')) {

					id = "Cat_" + id;
					$("#" + id).addClass("selected_category");
				}
				else {
					if (controller == 'Home')
						$("#Cat_Home").addClass("selected_category");
				}

			});

		</script>


	</head>



	<body>

<div id="header">
	<h1>Smart Blog</h1>
@*	<h3 style="margin-left:20px;">Blog categories</h3>*@
	<ul>
		<li><a id="Cat_Home" href="~/Home">Home</a></li>
		@foreach (var item in Model.Categories)
		{ 
			<li>
				<a id="@("Cat_" + item.Id)" href="~/Home/Categories/@item.Id">@item.Name</a>
			</li>
		}

	</ul>
	<p id="layoutdims">
		<span style="float:left;display:@(HttpContext.Current.User.Identity.IsAuthenticated ? "block" : "none")">Welcome @HttpContext.Current.User.Identity.Name</span>
		@Html.ActionLink("Admin","Index","BlogAdmin")
	</p>
</div>
<div class="colmask leftmenu">
	<div class="colleft">
		<div class="col1">
			<!-- Column 1 start -->

			@RenderSection("featured", required: false)

			<div id="body">
				@RenderBody()
			</div>

			<!-- Column 1 end -->
		</div>
		<div class="col2">
			<!-- Column 2 start -->
			<div id="ads">
				<a href="~/Home">
					<img src="@Url.Content("~/Images/BlogImage.jpg")" width="125" border="0" height="125" alt="" />
				</a>
			</div>
			<h2>Latest Blog posts</h2>
			<ul style="padding-left:15px;">
				<!--Blog list (last 10..) -->
				@foreach (var blog in Model.Blogs.OrderByDescending(p=>p.CreatedDate))
				{ 
					<li>
						<a href="~/Blog/Index/@blog.Id">@(blog.Title + " " + "(" + blog.CreatedDate + ")")</a>
					</li>
					
				}
			</ul>
			<h2>Tags</h2>
				@{Html.RenderAction("TagListFull", "BlogAdminHelper");}

			<!-- Column 2 end -->
		</div>
	</div>
</div>
		<div id="footer">
		<p>Alexey Geller, 2012-2013</p>
</div>


		@RenderSection("scripts", required: false)
	</body>
</html>

MvcBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>